on: push
jobs:
  build:
    runs-on: windows-latest

    steps:
#      - name: Setting up Java
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#
#      - name: Set up Maven
#        uses: actions/setup-java@v3
#        with:
#          maven-version: '3.9.9'

      - name: git branch check
        run: git branch
        
