on: push
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # - name: Setting up Java
      #   uses: actions/setup-java@v3
      #   with:
      #     java-version: '17'
      #     distribution: 'adoptium'

      - name: Check Maven and Java versions
        run: |
          java -version
          mvn -v

      - name: Install dependencies and run tests
        run: mvn test

      - name: Push changes if tests pass
        if: success()
        run: git push origin main
