on: push
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Verify Java Installation
        run: java -version

  #no need now, because i am running local DB so it won't pass this on the pipeline
#      - name: Install dependencies and run tests
#        run: mvn test
