on: push
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Download and Install Java 17
        run: |
          curl -Lo openjdk-17.zip https://github.com/adoptium/temurin17-binaries/releases/latest/download/OpenJDK17U-jdk_x64_windows_hotspot.zip
          mkdir java-17
          tar -xf openjdk-17.zip -C java-17 --strip-components=1
          echo "JAVA_HOME=$PWD/java-17" >> $GITHUB_ENV
          echo "$JAVA_HOME/bin" >> $GITHUB_PATH

      - name: Verify Java Installation
        run: java -version

      - name: Install dependencies and run tests
        run: mvn test

      - name: Push changes if tests pass
        if: success()
        run: git push origin main
