on: push
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Java JDK
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' 
          java-version: '17'     

      - name: Verify Java Installation
        run: java -version

      - name: Install dependencies and run tests
        run: mvn test

      - name: Push changes if tests pass
        if: success()
        run: git push origin main
